INSERT INTO airport (icao, name, country) VALUES
('CYYZ','Lester B. Pearson International Airport','CA'),
('CYVR','Vancouver International Airport','CA'),
('CYWG','Winnipeg International Airport','CA'),
('KDCA','Ronald Reagan Washington National Airport','US'),
('KJFK','John F Kennedy Airport','US'),
('KMCI','Kansas City International Airport','US'),
('KLAX','Los Angeles International Airport','US'),
('KMIA','Miami International Airport','US'),
('KSEA','Seattle Tacoma International Airport','US'),
('MMMX','Licenciado Benito Juarez International Airport','MX'),
('MMUN','Cancun International Airport','MX'),
('MMTJ','General Abelardo L. Rodriguez International Airport','MX'),
('MUHA','Jose Marti International Airport','CU'),
('MKJP','Norman Manley International Airport','JM'),
('MRLB','Guanacaste Airport','CR'),
('MYNN','Lynden Pindling International Airport','BS'),
('MDSD','Las America International Airport','DO'),
('MSLP','Monseñor Óscar Arnulfo Romero International Airport','SV'),
('EFHK','Helsinki Vantaa Airport','FI'),
('LEBL','Josep Tarradellas Barcelona-El Prat Airport','ES'),
('LEMD','Adolfo Suárez Madrid–Barajas Airport','ES'),
('LFMN','Nice-Côte d''Azur Airport','FR'),
('LFPO','Paris-Orly Airport','FR'),
('EDDF','Frankfurt am Main Airport','DE'),
('EDDB','Berlin Brandenburg Airport','DE'),
('EDDM','Munich Airport','DE'),
('LGAV','Athens Eleftherios Venizelos International Airport','GR'),
('LGTS','Thessaloniki Macedonia International Airport','GR'),
('LOWW','Vienna International Airport','AT'),
('EGLL','London Heathrow Airport','GB'),
('EGPH','Edinburgh Airport','GB'),
('LIRF','Rome–Fiumicino Leonardo da Vinci International Airport','IT'),
('LICJ','Falcone–Borsellino Airport','IT'),
('LIMC','Malpensa International Airport','IT'),
('ESSA','Stockholm Arlanda Airport','SE'),
('ESGG','Gothenburg-Landvetter Airport','SE'),
('UKBB','Boryspil International Airport','UA'),
('UKLL','Lviv International Airport','UA'),
('EPWA','Warsaw Chopin Airport','PL'),
('EPKK','Kraków John Paul II International Airport','PL'),
('EPGD','Gdańsk Lech Wałęsa Airport','PL'),
('LYBE','Belgrade Nikola Tesla Airport','RS'),
('VVTS','Tan Son Nhat International Airport','VN'),
('VVNB','Noi Bai International Airport','VN'),
('RJTT','Tokyo Haneda International Airport','JP'),
('RJCC','New Chitose Airport','JP'),
('RJFF','Fukuoka Airport','JP'),
('ZBAA','Beijing Capital International Airport','CN'),
('ZUCK','Chongqing Jiangbei International Airport','CN'),
('ZLXY','Xi’an Xianyang International Airport','CN'),
('ZWWW','Urumqi Diwopu International Airport','CN'),
('ULLI','Pulkovo Airport','RU'),
('UUEE','Sheremetyevo International Airport','RU'),
('UNKL','Krasnoyarsk International Airport','RU'),
('UHWW','Vladivostok International Airport','RU'),
('UNNT','Novosibirsk Tolmachevo Airport','RU'),
('VIDP','Indira Gandhi International Airport','IN'),
('VABB','Chhatrapati Shivaji International Airport','IN'),
('VOMM','Chennai International Airport','IN'),
('OERK','King Khalid International Airport','SA'),
('OEMA','Prince Mohammad Bin Abdulaziz Airport','SA'),
('LTAC','Esenboga International Airport','TR'),
('LTAI','Antalya International Airport','TR'),
('LTBJ','Adnan Menderes International Airport','TR'),
('OIII','Mehrabad International Airport','IR'),
('OISS','Shiraz Shahid Dastghaib International Airport','IR'),
('UAAA','Almaty International Airport','KZ'),
('UACC','Nursultan Nazarbayev International Airport','KZ'),
('WIII','Soekarno-Hatta International Airport','ID'),
('WADD','Ngurah Rai (Bali) International Airport','ID');